### ISSUE TITLE
Add to bioconda?

### ISSUE THREAD

**Issue by karl616** [kundajelab/phantompeakqualtools#10]
Should this be added to bioconda?

If so, how modified is the SPP version? Would it be possible to make use of the SPP already in bioconda?
In your atac-seq-pipeline, you use r-spp v1.13. Is that sufficient?

**Comment by karl616** [comment]
In order to this, a license is needed. Is this something you have thought about?

**Comment by akundaje** [comment]
Good point. We'll add the license info to the GitHub.

**Comment by leepc12** [comment]
@karl616 Thanks for your work, just added a license file. I am still working on the installation script for pipelines let's talk there.

**Comment by karl616** [comment]
@leepc12 I'll try to keep my communication more centralized...

For reference, this is the pull request to add phantompeakqualtools to bioconda:
https://github.com/bioconda/bioconda-recipes/pull/10171

**Comment by karl616** [comment]
phantompeakqualtools is now merged in and available in bioconda. With the bioconda repository correctly configured it can be installed with:

`conda install phantompeakqualtools`

With that I'll close this issue.
