### ISSUE TITLE
install.packages("./spp_1.14.tar.gz"), error.

### ISSUE THREAD

**Issue by zhenyisong** [kundajelab/phantompeakqualtools#4]
I googled this chat, install.packages("./spp_1.14.tar.gz"). The[ post  here](https://groups.google.com/forum/#!topic/idr-discuss/XsjeWCwGxG0) complained that the package cannot be installed. I replicated the same error <inferring 'repos = NULL' from 'pkgs' Error in getOctD(x, offset, len) : invalid octal digit>. Is there any progress on this issue or I should upgrade some additional packages? Thanks.

**Comment by leepc12** [comment]
I just replied to the posting on the google group. Please let me know if that works.

**Comment by zhenyisong** [comment]
I rechecked the downloaded package for this spp version from the Github. I thought I used the wget command and got the source code. But this is in fact a fake file in txt format. Anyway, thanks.
