### ISSUE TITLE
Getting lots of compilation errors on install

### ISSUE THREAD

**Issue by endrebak** [kundajelab/phantompeakqualtools#8]
```
# ... many more error messages removed - last one fatal
bed2vector.cpp:2530:77: error: qualified-id in declaration before 'li'
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:2532:10: error: 'li' was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:2532:23: error: request for member 'end' in 'cind_map', which is of non-class type 'int'
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:2536:10: error: no match for 'operator[]' (operand types are 'int' and 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}')
  cind_map[chr]=cind;
          ^
/mnt/work/endrebak/software/anaconda/lib/R/etc/Makeconf:167: recipe for target 'bed2vector.o' failed
make: *** [bed2vector.o] Error 1
ERROR: compilation failed for package 'spp'
* removing '/mnt/work/endrebak/software/anaconda/lib/R/library/spp'
```

**Comment by leepc12** [comment]
What is your R version? and did you install Boost library?

There is a workaround for this issue. You can use a dependency installer in our ChIP-seq pipeline, which includes phantompeakqualtools and its dependencies (R and all R packages related to it).

1) Install Conda first (https://github.com/kundajelab/chipseq_pipeline#conda)
2) Install dependencies for the pipeline (https://github.com/kundajelab/chipseq_pipeline#dependencies)
3) Activate conda environment (`$ source activate aquas_chipseq`)
4) Run Rscript

**Comment by endrebak** [comment]
Thank you for replying. I am using anaconda R with boost and R-cpp.  

I guess I should try your install script, but I became wary because of this warning:

```
REMOVE ANY ANACONDA OR OTHER VERSIONS OF CONDA FROM YOUR BASH STARTUP SCRIPT. WE CANNOT GUARANTEE THAT PIPELINE WORKS WITH OTHER VERSIONS OF CONDA. ALSO REMOVE R AND OTHER CONFLICTING MODULES FROM IT TOO. 
```

There does not seem to be anything in the install script that would mess with my existing conda though - it just install loads of stuff under a new environment.

**Comment by leepc12** [comment]
Please ignore that warning and proceed to install it, if something wrong happens then let me know.

**Comment by endrebak** [comment]
So this is not it?
https://github.com/kundajelab/chip-seq-pipeline2/blob/master/installers/install_dependencies.sh

I mean, you seem to have a new pipeline, but I should still use the installer in the old repo?

**Comment by endrebak** [comment]
I get the same error with `/mnt/work/endrebak/software/anaconda/envs/aquas_chipseq/bin/R CMD INSTALL spp_1.14.tar.gz`.

**Comment by leepc12** [comment]
spp is already installed in the conda environment aquas_chipseq.

Jin

**Comment by endrebak** [comment]
Haha, thanks. I can be dumb XD

**Comment by endrebak** [comment]
It worked beautifully - thanks for your patience and help :)
